# configuration file for wd_search.py for general use, assumes we are only interested in English

CACHE_SIZE: 4096

# defaults for searching

# set of languages for which we want the name, aliases and descriptions 
LANGS:
  - en

# types a result should have to be ranked at the top.  These are ones
# we are looking for, typically becuase the NLP system tags entities as
# being one of these.

TARGET_TYPES:
   - MESH    # infered type for items with a P486 property

# common confusions for a possible target type, for example SpaCy
# often consuses a LOC for a FAC and vice versa
NEAR_MISS_TYPES:
  PERSON:
  - ORG
  ORG:
  - PERSON
  GPE:
  - LOC
  - FAC
  LOC:
  - FAC
  - GPE
  FAC:
  - LOC
  - GPE
  PRODUCT:
   - ENTITY

#second best types
GOOD_TYPES:
  - disease
  - 'infectious disease'
  -  protein
  -  'chemical compound'
  -  taxon
  -  biotechnology
  -  gene
  - 'medical procedure'
  -  strain
  - 'disease causative agent'
  - 'immunization safety'
  -  'clinical trial'
  - 'vaccine type'
  - 'type of statistic'

# types a result can have to be included even it it does not have a target type or good type
OK_TYPES: 
  -  ENTITY
  -  EVENT
  -  FAC
  -  GPE
  -  LOC
  -  NORP
  -  ORG
  -  PERSON
  -  PRODUCT



# types a result must *not* have
BAD_TYPES:
  - wikijunk
  - timeZone
  - WIKIDISAMBIGUATION
  - fictional
  - ARTICLE
  - PUBLICATION
  - SONG
  - MUSIC
  - genre
  - NAME 
  - WRTITTENWORK
  -  WORK_OF_ART
  - 'performing arts group'
  - 'sports organization'

# default search language (2-letter language code)
SEARCH_LANGUAGE: "en"

# should we lemmatize  the tokens in search strings
LEMMATIZE_SEARCH_STRING: True

# ensure that the search string is ascii by removing any other characters
DECODE_TO_ASCII: True

REMOVE_SPECIAL_CHARS: True
SPECIAL_CHARS:  ")(%"

# default wikidata fields for the initial search use, on of:  label_aliases,  label_aliases_description
#SEARCH_ACTION: label_aliases
SEARCH_ACTION:  label_aliases_description        # and more!

# Maximum results initial search should return
LIMIT: 20

# how many results should final search return
TOP: 4

# included DBpedia abstract?
DBPEDIA: False

# item category, one of: all, strictinstance, instance, strictconcept, concept
CATEGORY: all

# default context string to score results (probably not needed)
CONTEXT: ''

# should we use context string (if provided) to score results?
USE_CONTEXT: True

# how to rank results, one of search, score, sum
RANKING: sum

DEBUG: False

# are we using this for the SCALE 2021?
SCALE: False

# what domain are we using this for
DOMAIN: Procure

# what SpaCy language model shioule we use, one of md, lg, trf, stanza
# the md one is pretty good.  It's similarity method will work better on non sentences.
LANGUAGE_MODEL: md

# give extra weight for candidates whose label is an exact match with the string 
PROMOTE_EXACT_LABEL_MATCH: True
