# configuration file for wd_search.py for general use, assumes we are only interested in English

CACHE_SIZE: 4096

# defaults for searching

# set of languages for which we want the name, aliases and descriptions 
LANGS:
  - en

# types a result should have to be ranked at the top
TARGET_TYPES:
  - ENTITY

GOOD_TYPES: []

# types a result can have to be included even it it does not have a target type
OK_TYPES: 
  -  ENTITY
#  -  AIRPORT
#  -  CARDINAL
  -  EVENT
  -  FAC
  -  GPE
#  -  LANGUAGE
  -  LAW
  -  LOC
# -  MIL
# -  MONEY
# -  NORP
  -  ORG
  -  PERSON
  -  PRODUCT
#   -  VEH
#   -  WEA
# - DATE
# - ORDINAL
#  - PERCENT
# - QUANTITY
# - TIME

NEAR_MISS_TYPES:
  PERSON:
  - ORG
  ORG:
  - PERSON
  GPE:
  - LOC
  - FAC
  LOC:
  - FAC
  - GPE
  FAC:
  - LOC
  - GPE
  PRODUCT:
   - ENTITY

# types a result must *not* have
BAD_TYPES:
  - wikijunk
  - timeZone
  - WIKIDISAMBIGUATION
  - FICTIONAL
  - ARTICLE
  - PUBLICATION
  - SONG
  - MUSIC
  - NAME 
#  - WRTITTENWORK
# -  WORK_OF_ART
  - 'performing arts group'

# default search language (2-letter language code)
SEARCH_LANGUAGE: "en"

# default wikidata fields for the initial search use, on of:  label_aliases,  label_aliases_description
#SEARCH_ACTION: label_aliases
SEARCH_ACTION:  label_aliases_description        # and more!

# Maximum results initial search should return
LIMIT: 15

# how many results should final search return
TOP: 3

# included DBpedia abstract?
DBPEDIA: False

# item category, one of: all, strictinstance, instance, strictconcept, concept
CATEGORY: all

# default context string to score results (probably not needed)
CONTEXT: ''

# should we use context string (if provided) to score results?
USE_CONTEXT: True

# how to rank results, one of search, score, sum
RANKING: sum

DEBUG: False

# are we using this for the SCALE 2021?
SCALE: False

# what SpaCy language model shioule we use, one of md, lg, trf, stanza
# the md one is pretty good.  It's similarity method will work better on non sentences.
LANGUAGE_MODEL: md





